# Generated by Django 3.0 on 2020-02-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20200204_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='a',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='b',
            new_name='paradigm',
        ),
        migrations.RemoveField(
            model_name='language',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='language',
            name='c',
        ),
        migrations.RemoveField(
            model_name='language',
            name='d',
        ),
    ]
