# Generated by Django 3.0 on 2020-02-04 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20200204_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='paradigm',
            new_name='a',
        ),
        migrations.AddField(
            model_name='language',
            name='b',
            field=models.CharField(default=datetime.date.today, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='c',
            field=models.CharField(default=datetime.date.today, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='d',
            field=models.CharField(default=datetime.date.today, max_length=50),
            preserve_default=False,
        ),
    ]
