# Generated by Django 3.0 on 2020-02-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_auto_20200204_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='Question',
            new_name='question',
        ),
    ]
